-- Additive generalized academic-rule architecture and Program 4 seed data.
BEGIN;
CREATE TABLE IF NOT EXISTS curriculum_components (
  component_id BIGSERIAL PRIMARY KEY, program_id VARCHAR NOT NULL REFERENCES programs(program_id),
  component_name TEXT NOT NULL, component_order INTEGER NOT NULL, required_credits NUMERIC,
  notes TEXT, UNIQUE(program_id, component_name));
CREATE TABLE IF NOT EXISTS curriculum_component_courses (
  component_id BIGINT NOT NULL REFERENCES curriculum_components(component_id),
  course_id VARCHAR NOT NULL REFERENCES courses(course_id), course_role TEXT NOT NULL DEFAULT 'REQUIRED',
  study_mode TEXT NOT NULL DEFAULT 'ALL', PRIMARY KEY(component_id, course_id, course_role, study_mode));
CREATE TABLE IF NOT EXISTS academic_rule_sets (
  rule_set_id BIGSERIAL PRIMARY KEY, program_id VARCHAR NOT NULL REFERENCES programs(program_id),
  rule_scope TEXT NOT NULL, rule_name TEXT NOT NULL, study_mode TEXT, exact_choice_count INTEGER,
  source_url TEXT, notes TEXT, UNIQUE(program_id, rule_scope, rule_name, study_mode));
CREATE TABLE IF NOT EXISTS academic_rule_groups (
  rule_group_id BIGSERIAL PRIMARY KEY, rule_set_id BIGINT NOT NULL REFERENCES academic_rule_sets(rule_set_id),
  parent_group_id BIGINT REFERENCES academic_rule_groups(rule_group_id), operator TEXT NOT NULL CHECK(operator IN ('AND','OR')),
  label TEXT, sort_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS academic_rule_conditions (
  condition_id BIGSERIAL PRIMARY KEY, rule_group_id BIGINT NOT NULL REFERENCES academic_rule_groups(rule_group_id),
  condition_type TEXT NOT NULL, subject_id TEXT, minimum_value NUMERIC, unit TEXT,
  accepted_values JSONB, parameters JSONB NOT NULL DEFAULT '{}'::jsonb, description TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS credit_requirements (
  credit_requirement_id BIGSERIAL PRIMARY KEY, program_id VARCHAR NOT NULL REFERENCES programs(program_id),
  component_id BIGINT REFERENCES curriculum_components(component_id), requirement_name TEXT NOT NULL,
  minimum_credits NUMERIC NOT NULL, study_mode TEXT, allows_external_courses BOOLEAN NOT NULL DEFAULT FALSE,
  approval_required BOOLEAN NOT NULL DEFAULT FALSE, notes TEXT, UNIQUE(program_id, requirement_name, study_mode));
CREATE TABLE IF NOT EXISTS credit_requirement_courses (
  credit_requirement_id BIGINT NOT NULL REFERENCES credit_requirements(credit_requirement_id),
  course_id VARCHAR NOT NULL REFERENCES courses(course_id), PRIMARY KEY(credit_requirement_id, course_id));
CREATE TABLE IF NOT EXISTS curriculum_substitutions (
  substitution_id BIGSERIAL PRIMARY KEY, program_id VARCHAR NOT NULL REFERENCES programs(program_id),
  study_mode TEXT NOT NULL, replaced_course_id VARCHAR REFERENCES courses(course_id),
  replacement_type TEXT NOT NULL, replacement_credits NUMERIC, description TEXT NOT NULL);
ALTER TABLE prerequisite_conditions ADD COLUMN IF NOT EXISTS parameters JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE prerequisite_conditions ADD COLUMN IF NOT EXISTS description TEXT;
SELECT setval('prerequisite_groups_prerequisite_group_id_seq', COALESCE((SELECT MAX(prerequisite_group_id) FROM prerequisite_groups), 1), true);
SELECT setval('prerequisite_conditions_prerequisite_condition_id_seq', COALESCE((SELECT MAX(prerequisite_condition_id) FROM prerequisite_conditions), 1), true);
INSERT INTO areas_of_study(area_id, area_name, status) VALUES ('ENG','Engineering','Active') ON CONFLICT (area_id) DO NOTHING;
INSERT INTO programs(program_id,program_name,program_overview,area_id,school,credential,program_level,study_mode,accepts_international_students,campus,delivery_method,status,source_url,notes)
VALUES ('8800BTECH','Construction Management','Bachelor of Technology Construction Management degree-completion program developing management, technical, and interpersonal construction-project skills.','ENG','School of Construction and the Environment','Bachelor of Technology / Bachelor''s Degree','Degree completion (Years 3 and 4)','Full-time and Part-time',TRUE,'Burnaby','In person','Active','https://www.bcit.ca/programs/construction-management-bachelor-of-technology-full-time-part-time-8800btech/','Two-year degree-completion program providing Years 3 and 4 of a four-year bachelor''s degree.')
ON CONFLICT (program_id) DO UPDATE SET program_name=EXCLUDED.program_name, program_overview=EXCLUDED.program_overview, area_id=EXCLUDED.area_id, school=EXCLUDED.school, credential=EXCLUDED.credential, program_level=EXCLUDED.program_level, study_mode=EXCLUDED.study_mode, campus=EXCLUDED.campus, delivery_method=EXCLUDED.delivery_method, status=EXCLUDED.status, source_url=EXCLUDED.source_url, notes=EXCLUDED.notes;

INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT7160','Statistics for Construction Management',3,'The construction industry uses statistical techniques to analyze business and engineering data. Topics include summarizing data; probability; the normal curve; sampling distribution; hypothesis testing; and linear regression and correlation. Upon successful completion, individuals will be able to intelligently read and interpret statistical material and use appropriate tools to perform various statistical calculations.','Active','https://www.bcit.ca/courses/statistics-for-construction-management-cmgt-7160/','Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT7190','Construction Planning and Controls',3,'Students will gain a deeper level of understanding of planning project work, and the application of the control processes, to manage and track progress towards the successful completion of project objectives. The ability to construct realistic schedules and justify project costs is imperative for construction managers in today''s competitive market. With the aid of industry management software (MS Project), students'' will generate scopes of work and specific task resourcing with a focus on the critical path. The control processes, tracking, gathering and analyzing project data, are some of the skills incorporated that will enable future managers'' to keep costs and schedules on track and mitigate potential risks.','Active','https://www.bcit.ca/courses/construction-planning-and-controls-cmgt-7190/','Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT7211','Heavy Equipment in Construction',3,'Heavy equipment and the tasks they perform are often the highest risk factors to project schedules and budgets. This course will provide students with tools and techniques used to analyze and evaluate project plans around the use of construction equipment on their projects. Course content is divided into two sections. In the first section, Equipment Management Plans & Principles students will review the basic factors around earthworks, site plan specifications and scopes of work in relation to planning for heavy equipment on project sites. The second section, Equipment Facts & Fundamentals, will investigate specific machine operations and the considerations to on-site production estimating. The ability to accurately calculate production and machine rates provide construction managers the opportunity to ensure schedules and budgets are within reason and to identify potential risk factors early on. Understanding the comprehensive nature of managing heavy equipment on project sites, of all sizes, is critical to maintaining schedules and costs on earthwork projects.','Active','https://www.bcit.ca/courses/heavy-equipment-in-construction-cmgt-7211/','50% in CMGT 7190 and  Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT7400','Project Planning for Quality & Risk Management',3,'This course takes a look at construction management processes and procedures over the life of a project with a focus on quality control and risk management. Identifying the project phases, the key milestones and deliverables at each phase, is critical to include in the project plans. Tracking, analyzing, and evaluating, progress to the milestones over the project''s lifecycle allows the management team to manage and mitigate both quality and risk factors in an organized and timely manner. Best practices and new concepts will be examined in order to enable students to formulate tools and techniques specific to their management styles and types of projects. This course also provides students with opportunities to further develop their presentation and report writing skills to meet industry expectations at the construction manager''s level.','Active','https://www.bcit.ca/courses/project-planning-for-quality-and-risk-management-cmgt-7400/','50% in CMGT 7211 and 50% in CMGT 7810, and Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('BUSA7250','Management Skills and Applications',3,'The course provides an overview of the basic skills of a manager and applies these skills through a series of projects and case studies. It examines the evolution of management and the organizational culture and environment. It also teaches the decision-making skills and the skills involved in planning, organizing, leading and controlling, including planning and facilitating change, teamwork, applying motivational techniques and effective communication.','Active','https://www.bcit.ca/courses/management-skills-and-applications-busa-7250/',NULL) ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT7330','Finance for Construction Managers',3,'An understanding of the fundamental concepts of accounting and financial analysis is essential for effective decision-making. Topics include the role of the financial manager in the organization, concepts and principles underlying accounting practices, financial statement reading and analysis, budgeting, accounting, time value of money, risk, and macro and micro economics.','Active','https://www.bcit.ca/courses/finance-for-construction-managers-cmgt-7330/','Admission to the BTech Construction Management degree program') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT7420','Construction Law',3,'This course covers the law that applies to the business of construction, and relates these concepts to the construction process by dealing with topical issues. The course teaches students about the theories of law, the Canadian legal system, business models, relationships between industry players, and how these concepts apply to the realm of the construction industry. The course further focuses on contract law, builders’ liens, insurance, bonding, and other issues of relative to the construction industry.','Active','https://www.bcit.ca/courses/construction-law-cmgt-7420/','50% in CMGT 7330 and Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT8435','Construction Enterprise Management',3,'Participants will be introduced to the primary elements of the start-up and management of a construction company. Start-up sections include strategic planning, business plan development and marketing. Construction management sections include strategic alignment, bidding, estimating, procurement, costing, changes to the contract and a communication workshop. Health and safety responsibilities of a construction project will be introduced from the perspective of the prime contractor.','Active','https://www.bcit.ca/courses/construction-enterprise-management-cmgt-8435/','Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT7535','Leadership and Interpersonal Skills',3,'Provides the essential skills to manage a diverse construction workforce. Factors influencing performance, personality, culture and organizational norms, as well as the practical application of modern management concepts and techniques will be discussed. Skills will be developed through lecture, casework, assignments and discussions. Students are expected to complete several leadership and interpersonal skills related to the assignments in class. These skill developments provide the opportunity for practical application of the key course concepts being taught. Students are expected to actively participate in small group exercises by: working in teams on assigned tasks, contributing their ideas and showing group effort, as well as following through on their commitments and tasks assigned and using effective communication skills appropriate for the situation.','Active','https://www.bcit.ca/courses/leadership-and-interpersonal-skills-cmgt-7535/','Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT7660','Environmental Considerations in Construction',3,'This course seeks to assist students to understand the complexities of how construction affects the environment, while looking at the environmental factors that affect construction. From sustainable construction, to building lifecycle assessments, and environmental impact to green energy technology and more; how construction projects are managed with consideration to the whole environment they are built in is vital in today''s world. Government legislation, Indigenous relations, stakeholder liability and project impacts to all will be discussed. Course material covers contaminated sites, the hazards, and site remediation. Construction methodologies to reduce pollution and waste, build green, LEED project stipulations, and practices to promote long term environmental protection are all key topics to construction managers in today''s marketplace.','Active','https://www.bcit.ca/courses/environmental-considerations-in-construction-cmgt-7660/','Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT8602','Engagement of Project Stakeholders',3,'​Stakeholders are varied and numerous in construction. Without some level of understanding of how the management team is addressing their needs, stakeholders have the capacity to affect the outcome of the projects. This course provides a systematic approach and comprehensive examination of internal and external stakeholder groups typical to construction projects. Case studies are utilized to demonstrate the potential impacts of stakeholders on industry projects.​','Active','https://www.bcit.ca/courses/engagement-of-project-stakeholders-cmgt-8602/','50% in CMGT 7535 and 50% in CMGT 7660 and 50% in CMGT 7810 and Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT7125','Construction Schedule and Delay Analysis',1,'In this course, the practical aspects of project scheduling and construction law will be emphasized. Students will examine construction delay examples and apply construction contract clauses to determine the type of delay, assign responsibility, and quantify damages. Course assignments and activities will help students to understand the types of construction delays and identify all of the costs that contribute to damages from a subcontractor, contractor, consultant and owner’s perspective.','Active','https://www.bcit.ca/courses/construction-schedule-and-delay-analysis-cmgt-7125/','50% in CMGT 7190 and Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT7220','Health and Safety in Construction',1,'Presents the role of key stakeholders involved in health and safety issues. Sessions will include: Legal framework for health and safety in Canada, philosophies and techniques for managing health and safety, the business benefits of health and safety, and the concepts of risk management and due diligence.','Active','https://www.bcit.ca/courses/health-and-safety-in-construction-cmgt-7220/','50% in CMGT 7205 and Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT7605','Industrial Relations',3,'Industrial relations will cover employment and collective bargaining legislation as well as maintenance of collective agreements and the management of industrial relations. The course will analyze employment standards legislation, the labour code, human rights, impact of collective bargaining / certification on organizational structure. The course will also look at negotiation, conflict management and team techniques. Students can expect to gain a solid understanding of what industrial relations is and why it is important to workers and management.','Active','https://www.bcit.ca/courses/industrial-relations-cmgt-7605/','Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT7840','Technical Presentations',1,'The ability to make an effective business presentation is more essential than ever for individuals wanting to advance in their careers. This course will describe to participants how to analyse audience need and then integrate a variety of presentation techniques to deliver an effective presentation.','Active','https://www.bcit.ca/courses/technical-presentations-cmgt-7840/','50% in CMGT 7100 and 50% in CMGT 7800 and Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT8040','Building - Civil Services',3,'The aim of the course is to enable students to develop knowledge and examination of civil services used in commercial and institutional buildings and their significance in the design and construction phases. The lectures will be delivered in 3 hour units per week by a qualified Professional Quantity Surveyor. The 3 hour units will be broken down into a 1 hour lecture and a 2 hour lab session allowing the student to work within a group context to assist learning and allowing question and answer time with the lecturer.','Active','https://www.bcit.ca/courses/building-civil-services-cmgt-8040/','50% in BLDT 2091 and 50% in CMGT 7205 and Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT8050','Budgeting/Conceptual Estimating',3,'The aim of the course is to enable students to develop knowledge and examination of various methods of conceptual estimating used in commercial and institutional buildings and their significance in the development of projects prior to the design and construction phases. The course will look at why budget/conceptual estimates are necessary, what factors need to be considered when preparing, evaluating and discussing project and operating costs during the early stages of a project when very little information is available and the design is very minimal. The course will also look at a number of different types of conceptual estimate, when to best use each and the limitations of the estimates types. The lectures will be delivered in 3 hour units per week by a qualified Professional Quantity Surveyor. The 3 hour units will be broken down into a 1 hour lecture and a 2 hour lab session allowing the student to work within a group context to assist learning and allowing question and answer time with the lecturer.','Active','https://www.bcit.ca/courses/budgeting-conceptual-estimating-cmgt-8050/','50% in BLDT 2091 and Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT8060','Risk Management in Design & Construction of Buildings',3,'Risk analysis and management in design and construction have, in the past, tended to depend mainly on intuition, judgment and experience. This course will help the student explore the subject of risk in a more objective manner, looking at both traditional risk management through the use of CPM/PERT/MSC and a more systematic analysis of defining, assessing and treating risk to help decisions to proceed and aid in managing the work. The lectures will be delivered in 3 hour units per week by a qualified Professional Quantity Surveyor. The 3 hour units will be broken down into a 1 hour lecture and a 2 hour lab session allowing the student to work within a group context to assist learning and allowing question and answer time with the lecturer.','Active','https://www.bcit.ca/courses/risk-management-in-design-and-construction-of-buildings-cmgt-8060/','50% in CMGT 7110 and 50% in CMGT 7330 and Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('EENG7000','Introduction to Climate Change, Ecology, and Systems Thinking',3,'This course presents the underpinning scientific concepts of contemporary environmental issues. It starts off with systems theory and ecosystem characteristics, including drivers for their change. More specifically, the course discusses deep ecology concepts and principles as they relate to human activities and their impacts on system functioning. The course further explores dimensions of integrated responses, including linkages of ecosystem services and human well-being. The course presents the most recent scientific evidence of the changing climate and evaluates industrial sectors - especially the energy sector - as the single largest anthropogenic source of climate‐changing greenhouse gas (GHG) emissions. The course explains and outlines principles of clean(er) technologies, industrial ecology and Life Cycle Assessment (LCA). Finally, the course provides the foundational concepts of environmental system analysis to learners who have no or limited specialized knowledge.','Active','https://www.bcit.ca/courses/introduction-to-climate-change-ecology-and-systems-thinking-eeng-7000/',NULL) ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('TMGT7101','Engineering, Technology and Management',1,'The course provides candidates with a perspective on the experience needed to assume a role in management in a technology-based organization. It will include some basic tools and techniques for the manager. The course is focused on those individuals who possess a formal technical education and are contemplating moving into management, or those who are already working in management positions. This course will examine how technologists and engineers can make the often difficult move from a technical specialist role to manager.','Active','https://www.bcit.ca/courses/engineering-technology-and-management-tmgt-7101/',NULL) ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('TMGT7102','Project Management/Resource Utilization',2,'This course focuses on the use of project management concepts and tools to accomplish business goals. Students will identify project management issues in rapidly changing business and technical environments and utilize strategies to manage projects effectively.','Active','https://www.bcit.ca/courses/project-management-resource-utilization-tmgt-7102/',NULL) ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('TMGT7111','High Technology Marketing Strategies',1,'This hands-on course will enable candidates to become knowledgeable about the various marketing strategies employed to create a successful market image for an organization. Drawing from industry examples of well-conceived and successful marketing strategies, students will gain a framework for developing viable strategies for their respective organizations.','Active','https://www.bcit.ca/courses/high-technology-marketing-strategies-tmgt-7111/',NULL) ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('TMGT7112','Marketing Research',1,'This course will enable students to develop a marketing research plan that will enable them to effectively examine the methods of assessing early market opportunities for high technology industrial and consumer products.','Active','https://www.bcit.ca/courses/marketing-research-tmgt-7112/','50% in TMGT 7111') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('TMGT7113','Marketing Programs and Plans',1,'These assignments and techniques are designed to enable people with no previous marketing experience to create a marketing plan within their own company. Students will have an opportunity to explore the application of programs in the context of the high technology markets.','Active','https://www.bcit.ca/courses/marketing-programs-and-plans-tmgt-7113/','50% in TMGT 7111') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('TMGT7121','Principles of Finance',1,'This course will equip candidates with an in-depth understanding of financing business undertakings, exploring sources of money, the role of business plans, equity capital, the role of debt financing, taxation issues, and cash investments.','Active','https://www.bcit.ca/courses/principles-of-finance-tmgt-7121/','50% in TMGT 7122') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('TMGT7124','Technology and International Finance',1,'This course deals with the major issues, institutions and instruments of international finance affecting technology transfer and the exchange of goods and services under contract. Course content addresses principal elements that include, but may not be limited to: instruments, institutions, legislative/regulatory frameworks and international finance variables.','Active','https://www.bcit.ca/courses/technology-and-international-finance-tmgt-7124/',NULL) ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('TMGT7134','Technology and International Trade and Competition',1,'The major thrust of this course is to describe how a technology firm may consider different options in the marketing of its technology in international markets. As the seller of the technology operates in a highly competitive environment, a clear understanding of the competitive forces and cultural dynamics at work in the global marketplace is critical to anyone seeking these export markets.','Active','https://www.bcit.ca/courses/technology-and-international-trade-and-competition-tmgt-7134/',NULL) ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('TMGT7143','Problem Solving and Decision-Making',1,'This course deals with a practical, hands-on approach to problem-solving and decision-making using an analytical, process-oriented approach. Different tools and techniques are used to better maximize the problem-solving and decision-making skills of the candidate. Opportunity is provided, by means of examples, for practice in creative thinking and problem-solving skills.','Active','https://www.bcit.ca/courses/problem-solving-and-decision-making-tmgt-7143/',NULL) ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('TMGT7144','Human Resource Planning and Control',1,'This course provides leaders with practical strategies and processes to develop a high performance work environment that values people. Each module will explore how to use human resource systems to effectively identify and address issues in the workplace. The course also addresses ways in which a technical manager may examine and enhance his or her own career. Time will be spent examining the relationship between the organization’s human resources needs and the ways in which these needs can be met through: HR Planning, Job Analysis and Design, Selection and Recruitment, Career Planning and Development, Performance Evaluation,Training and Development.','Active','https://www.bcit.ca/courses/human-resource-planning-and-control-tmgt-7144/',NULL) ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('TMGT7145','Leadership in a World of Change',3,'This course highlights the practices of effective leadership and the dynamics of the change process with a view to the interdependence of these two forces. The course differentiates between management and leadership, exploring the need for each aspect while continuing to strive for business goals and engaging in change aimed at improving company effectiveness. Effective leaders are able to resolve problems, conflicts in the workplace and envision an inspiring course of innovation, this course provides practical strategies which can be implemented in any work environment. The course is experiential, so regardless of current leadership ability each learner will be able to actively enhance their own leadership skills.','Active','https://www.bcit.ca/courses/leadership-in-a-world-of-change-tmgt-7145/',NULL) ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('LIBS7001','Critical Reading and Writing',3,'This is a course in advanced composition and rhetoric, in which students will develop skills in complex critical analysis and interpretation by analyzing and evaluating materials from a variety of discourses or genres, including visual, online, and print; developing and writing essays, including critiques and research papers; applying and discussing principles of rhetoric and critical theory; examining and using methods of interpretation and analysis from the humanities and social sciences; evaluating the credibility of primary and secondary sources, including as it applies to media literacy, and for the purposes of academic research; situating discourses within their historical context and relevant to rhetorical theories of different periods (for example, Aristotle in the ancient world and Bakhtin in the twentieth century). The course format will include lecture, discussion, and both individual and group activities.','Active','https://www.bcit.ca/courses/critical-reading-and-writing-libs-7001/','50% in BCIT ENGL 1177 or equivalent, or 6 credits BCIT Communication at 1100-level or above, or 3 credits of a university/college first-year social science or humanities course.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('LIBS7002','Applied Ethics',3,'Fosters abilities and values required for ethical decision making at work. Develops skills in logical analysis, a working knowledge of moral principles and theories, and the ability to diagnose and resolve moral disagreements commonly found at work. Examines and applies moral principles to historically famous cases in manufacturing, human resources, management, engineering, health care, and computing.','Active','https://www.bcit.ca/courses/applied-ethics-libs-7002/','BCIT ENGL 1177, or 6 credits BCIT Communication at 1100-level or above, or 3 credits of a university/college first-year social science or humanities course.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('LIBS7013','Race, Class and Gender: Intersections',3,'The course explores race, gender, and class as intersecting relations that have applicability to academic and working contexts, as well as and applicability to our everyday lives and relationships. Concepts and arguments from the social sciences and humanities dealing with race, gender, and class in inter-related combinations not just as stand-alone concepts will be studied and applied in the course. Course material will focus on but not be limited to Canada and the US. Course material will also have an emphasis on aboriginal issues in Canada. Students will gain opportunities to critically reflect on their own situatedness within these intersections. Additionally, students will learn strategies for critical self-awareness, response, and alliance building that they can take to communities where they work and live.','Active','https://www.bcit.ca/courses/race-class-and-gender-intersections-libs-7013/','BCIT ENGL 1177, or 6 credits BCIT Communication at 1100-level or above, or 3 credits of a university/college first-year social science or humanities course.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT7810','Advanced Industry Communication',3,'Oral and written communication is a major component of the roles and responsibilities of a construction manager. From negotiating contracts, to explaining scopes of work, directing employees to reporting project status, change orders and financial updates to clients; effective and professional communication will help you to gain commitment and buy-in from the variety of stakeholders engaged with every day. This course will provide you opportunities to build on your general communication skills, as well as report writing and presentation skills. The course will focus on the overall structure, organization of information and the logical progression of concepts.','Active','https://www.bcit.ca/courses/advanced-industry-communication-cmgt-7810/','Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT8211','Industry Collaborations',3,'The goal of this course is to provide an overview of the expanse of the type of construction projects, construction manager roles, typical methodologies, and the direction, and types of new technologies in the industry. Through a collective approach instructors, industry representatives, and students, will be encouraged to share ideas on key and current construction management topics. The topics will be chosen from the programs courses, and are intended to expand on these learnings. We will be looking at industry norms, new technologies and future directions on a variety of construction related topics. Subject matter experts and construction professionals will present on behalf of their organizations, instructors will assist with the development of class exercises and group discussions.','Active','https://www.bcit.ca/courses/industry-collaborations-cmgt-8211/','50% in CMGT 7810 and 50% in CMGT 7660 and Admission to the BTech Construction Management degree program.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT8700','Industry Based Project Proposal',1,'The goal of this course is to design and develop a formal proposal that will be the student''s plan for the final program course, CMGT 8800. Students must present a topic that is innovative, experimental or exploratory in their work context. The intent of the course deliverable, a professional project proposal, is to clearly outline the student''s topic, objectives, methodologies, research requirements, schedule, and project deliverables. The project proposal will be held to the highest standards. It is recommended that this course be taken immediately prior to registering for CMGT 8800, Industry Based Project.','Active','https://www.bcit.ca/courses/industry-based-project-proposal-cmgt-8700/','Successful completion of all program courses (with exception of CMGT 8800). Corequisites: Minimum of 2 years Related Work Experience; Industry Topic; and an Industry Sponsor.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT8800','Industry Based Project*',6,'The goal of this course is to provide the student with an opportunity to work independently on an applied research project associated with a construction industry issue or procedure. Students work closely with an industry sponsor, under the mentorship of a faculty advisor to execute the research proposal that was developed in CMGT 8700. The students'' pre-approved proposal outlines the project scope, goals, methods, and deliverables that forms the basis for this course. This course is intended to assess the students'' ability to integrate the skills and knowledge gained from the Program with their individual work experience and apply these in a real-world context. In conjunction with an industry sponsor, the student solves a technical problem relating to construction. The research project must contain elements that are innovative, experimental, or exploratory in nature. A faculty advisor will supervise the progress of the project, provide guidance and direction where appropriate and evaluate the final report and its presentation. The faculty advisor submits their evaluation and the final grade is determined collaboratively with the Department.','Active','https://www.bcit.ca/courses/industry-based-project-cmgt-8800/','50% in CMGT 8700 and Department approval.') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO courses(course_id,course_name,credits,course_overview,status,source_url,notes) VALUES ('CMGT8810','Industry Based Project*',4,'The goal of this course is to provide the student with an opportunity to work independently on an applied research project associated with a construction industry issue or procedure. Students work closely with an industry sponsor, under the mentorship of a faculty advisor to execute the research proposal that was developed in CMGT 8700. The students'' pre-approved proposal outlines the project scope, goals, methods, and deliverables that forms the basis for this course. This course is intended to assess the students'' ability to integrate the skills and knowledge gained from the Program with their individual work experience and apply these in a real-world context. In conjunction with an industry sponsor, the student solves a technical problem relating to construction. The research project must contain elements that are innovative, experimental, or exploratory in nature. A faculty advisor will supervise the progress of the project, provide guidance and direction where appropriate and evaluate the final report and its presentation. The faculty advisor submits their evaluation and the final grade is determined collaboratively with the Department.','Active','https://www.bcit.ca/courses/industry-based-project-cmgt-8810/','50% in CMGT 8700 and Departmental approval') ON CONFLICT(course_id) DO UPDATE SET course_name=EXCLUDED.course_name,credits=EXCLUDED.credits,course_overview=EXCLUDED.course_overview,status=EXCLUDED.status,source_url=EXCLUDED.source_url,notes=EXCLUDED.notes;
INSERT INTO curriculum_components(program_id,component_name,component_order,required_credits) VALUES ('8800BTECH','Construction Controls and Techniques',1,NULL) ON CONFLICT(program_id,component_name) DO UPDATE SET component_order=EXCLUDED.component_order,required_credits=EXCLUDED.required_credits;
INSERT INTO curriculum_components(program_id,component_name,component_order,required_credits) VALUES ('8800BTECH','Organization Management',2,12) ON CONFLICT(program_id,component_name) DO UPDATE SET component_order=EXCLUDED.component_order,required_credits=EXCLUDED.required_credits;
INSERT INTO curriculum_components(program_id,component_name,component_order,required_credits) VALUES ('8800BTECH','Stakeholder Engagement',3,9) ON CONFLICT(program_id,component_name) DO UPDATE SET component_order=EXCLUDED.component_order,required_credits=EXCLUDED.required_credits;
INSERT INTO curriculum_components(program_id,component_name,component_order,required_credits) VALUES ('8800BTECH','Management Electives',4,4) ON CONFLICT(program_id,component_name) DO UPDATE SET component_order=EXCLUDED.component_order,required_credits=EXCLUDED.required_credits;
INSERT INTO curriculum_components(program_id,component_name,component_order,required_credits) VALUES ('8800BTECH','Liberal Studies Component',5,12) ON CONFLICT(program_id,component_name) DO UPDATE SET component_order=EXCLUDED.component_order,required_credits=EXCLUDED.required_credits;
INSERT INTO curriculum_components(program_id,component_name,component_order,required_credits) VALUES ('8800BTECH','Professional Standards',6,11) ON CONFLICT(program_id,component_name) DO UPDATE SET component_order=EXCLUDED.component_order,required_credits=EXCLUDED.required_credits;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT7160','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Construction Controls and Techniques' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT7190','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Construction Controls and Techniques' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT7211','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Construction Controls and Techniques' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT7400','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Construction Controls and Techniques' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'BUSA7250','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Organization Management' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT7330','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Organization Management' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT7420','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Organization Management' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT8435','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Organization Management' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT7535','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Stakeholder Engagement' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT7660','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Stakeholder Engagement' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT8602','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Stakeholder Engagement' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT7125','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT7220','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT7605','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT7840','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT8040','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT8050','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT8060','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'EENG7000','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'TMGT7101','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'TMGT7102','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'TMGT7111','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'TMGT7112','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'TMGT7113','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'TMGT7121','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'TMGT7124','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'TMGT7134','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'TMGT7143','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'TMGT7144','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'TMGT7145','ELECTIVE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'LIBS7001','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Liberal Studies Component' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'LIBS7002','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Liberal Studies Component' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'LIBS7013','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Liberal Studies Component' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT7810','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Professional Standards' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT8211','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Professional Standards' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT8700','REQUIRED' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Professional Standards' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT8800','CHOICE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Professional Standards' ON CONFLICT DO NOTHING;
INSERT INTO curriculum_component_courses(component_id,course_id,course_role) SELECT component_id,'CMGT8810','CHOICE' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Professional Standards' ON CONFLICT DO NOTHING;

INSERT INTO program_offerings(offering_id,program_id,study_mode,campus,delivery_method,application_type,application_status,source_url,notes) VALUES
('8800BTECH-FT-SEP','8800BTECH','Full-time','Burnaby','In person','Planned Program','Active','https://www.bcit.ca/programs/construction-management-bachelor-of-technology-full-time-part-time-8800btech/','September intake'),
('8800BTECH-PT-JAN','8800BTECH','Part-time','Burnaby','In person','Flexible Learning','Active','https://www.bcit.ca/programs/construction-management-bachelor-of-technology-full-time-part-time-8800btech/','January intake'),
('8800BTECH-PT-APR','8800BTECH','Part-time','Burnaby','In person','Flexible Learning','Active','https://www.bcit.ca/programs/construction-management-bachelor-of-technology-full-time-part-time-8800btech/','April intake'),
('8800BTECH-PT-SEP','8800BTECH','Part-time','Burnaby','In person','Flexible Learning','Active','https://www.bcit.ca/programs/construction-management-bachelor-of-technology-full-time-part-time-8800btech/','September intake') ON CONFLICT(offering_id) DO UPDATE SET notes=EXCLUDED.notes;

INSERT INTO credit_requirements(program_id,component_id,requirement_name,minimum_credits,allows_external_courses,approval_required,notes)
SELECT '8800BTECH',component_id,'Management elective credits',4,TRUE,TRUE,'Approved external management courses may satisfy this requirement.' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Management Electives' ON CONFLICT(program_id,requirement_name,study_mode) DO NOTHING;
INSERT INTO credit_requirement_courses(credit_requirement_id,course_id)
SELECT cr.credit_requirement_id, ccc.course_id FROM credit_requirements cr JOIN curriculum_component_courses ccc ON ccc.component_id=cr.component_id WHERE cr.program_id='8800BTECH' AND cr.requirement_name='Management elective credits' ON CONFLICT DO NOTHING;
INSERT INTO credit_requirements(program_id,component_id,requirement_name,minimum_credits,notes)
SELECT '8800BTECH',component_id,'Liberal Studies total',12,'9 mandatory credits plus 3 elective credits.' FROM curriculum_components WHERE program_id='8800BTECH' AND component_name='Liberal Studies Component' ON CONFLICT(program_id,requirement_name,study_mode) DO NOTHING;
INSERT INTO curriculum_substitutions(program_id,study_mode,replaced_course_id,replacement_type,replacement_credits,description)
SELECT '8800BTECH','Part-time','LIBS7013','CREDIT_POOL',3,'Part-time students may take 3 additional approved Liberal Studies elective credits instead of LIBS 7013.' WHERE NOT EXISTS (SELECT 1 FROM curriculum_substitutions WHERE program_id='8800BTECH' AND study_mode='Part-time' AND replaced_course_id='LIBS7013');

-- Admission: common requirements AND exactly one complete pathway.
WITH rs AS (INSERT INTO academic_rule_sets(program_id,rule_scope,rule_name,exact_choice_count,source_url,notes) VALUES ('8800BTECH','ADMISSION','Construction Management admission',1,'https://www.bcit.ca/programs/construction-management-bachelor-of-technology-full-time-part-time-8800btech/#entry','Mandatory pre-entry assessment, common English, and exactly one of four pathways.') ON CONFLICT(program_id,rule_scope,rule_name,study_mode) DO UPDATE SET exact_choice_count=1 RETURNING rule_set_id),
root AS (INSERT INTO academic_rule_groups(rule_set_id,operator,label,sort_order) SELECT rule_set_id,'AND','Admission requirements',1 FROM rs RETURNING rule_group_id,rule_set_id),
paths AS (INSERT INTO academic_rule_groups(rule_set_id,parent_group_id,operator,label,sort_order) SELECT rule_set_id,rule_group_id,'OR','Exactly one entry pathway',3 FROM root RETURNING rule_group_id,rule_set_id)
INSERT INTO academic_rule_conditions(rule_group_id,condition_type,subject_id,minimum_value,unit,description,sort_order)
SELECT root.rule_group_id,v.* FROM root CROSS JOIN (VALUES
('PRE_ENTRY_ASSESSMENT',NULL,NULL,NULL,'Approved departmental pre-entry assessment before application',1),
('ENGLISH_GRADE','ENGLISH_STUDIES_12',73,'PERCENT','English Studies 12 at 73% or equivalent',2)) v(condition_type,subject_id,minimum_value,unit,description,sort_order);

DO $$ DECLARE rs BIGINT; paths BIGINT; g BIGINT; BEGIN
SELECT rule_set_id INTO rs FROM academic_rule_sets WHERE program_id='8800BTECH' AND rule_scope='ADMISSION';
SELECT rule_group_id INTO paths FROM academic_rule_groups WHERE rule_set_id=rs AND label='Exactly one entry pathway';
FOR g IN SELECT rule_group_id FROM academic_rule_groups WHERE rule_set_id=rs AND parent_group_id=paths LOOP DELETE FROM academic_rule_conditions WHERE rule_group_id=g; DELETE FROM academic_rule_groups WHERE rule_group_id=g; END LOOP;
INSERT INTO academic_rule_groups(rule_set_id,parent_group_id,operator,label,sort_order) VALUES(rs,paths,'AND','Pathway A',1) RETURNING rule_group_id INTO g;
INSERT INTO academic_rule_conditions(rule_group_id,condition_type,minimum_value,unit,description,sort_order) VALUES(g,'RELATED_POSTSECONDARY_CREDENTIAL_GPA',67,'PERCENT','Construction-related diploma or degree from a recognized institution with minimum 67% GPA',1),(g,'WORK_EXPERIENCE',1,'YEAR','At least 1 year construction-industry work experience',2);
INSERT INTO academic_rule_groups(rule_set_id,parent_group_id,operator,label,sort_order) VALUES(rs,paths,'AND','Pathway B',2) RETURNING rule_group_id INTO g;
INSERT INTO academic_rule_conditions(rule_group_id,condition_type,minimum_value,unit,description,sort_order) VALUES(g,'UNRELATED_POSTSECONDARY_CREDENTIAL_GPA',67,'PERCENT','Unrelated diploma or degree from a recognized institution with minimum 67% GPA',1),(g,'BRIDGING_CREDENTIAL_GPA',67,'PERCENT','BCIT Construction Operations Associate Certificate with minimum 67% GPA',2),(g,'WORK_EXPERIENCE',1,'YEAR','At least 1 year construction-industry work experience',3);
INSERT INTO academic_rule_groups(rule_set_id,parent_group_id,operator,label,sort_order) VALUES(rs,paths,'AND','Pathway C',3) RETURNING rule_group_id INTO g;
INSERT INTO academic_rule_conditions(rule_group_id,condition_type,minimum_value,unit,parameters,description,sort_order) VALUES(g,'UNRELATED_POSTSECONDARY_CREDENTIAL_GPA',67,'PERCENT','{}','Unrelated diploma or degree from a recognized institution with minimum 67% GPA',1),(g,'WORK_EXPERIENCE',8,'YEAR','{"region":"North America","role_level":"mid_or_senior","field":"construction management"}','At least 8 years North American construction-management experience in mid/senior roles',2);
INSERT INTO academic_rule_groups(rule_set_id,parent_group_id,operator,label,sort_order) VALUES(rs,paths,'AND','Pathway D',4) RETURNING rule_group_id INTO g;
INSERT INTO academic_rule_conditions(rule_group_id,condition_type,minimum_value,unit,accepted_values,parameters,description,sort_order) VALUES
(g,'RED_SEAL_TRADE',NULL,NULL,'["cabinetmaker","carpenter","electrician","industrial mechanic/millwright","metal fabricator","plumber","refrigeration & air conditioning mechanic","welder level A"]','{}','Approved Red Seal trade',1),
(g,'MATH_OPTION_GRADE',60,'PERCENT','["Pre-Calculus 11","Foundations Math 11","Workplace Math 11","BLDT 1011","accepted BC/Yukon equivalent"]','{}','One accepted math option at 60%',2),
(g,'BRIDGING_CREDENTIAL_GPA',67,'PERCENT',NULL,'{}','Construction Operations Associate Certificate with minimum 67% GPA',3),
(g,'WORK_EXPERIENCE',1,'YEAR',NULL,'{"excludes":"apprenticeship hours","field":"construction industry"}','At least 1 year construction-industry experience in addition to apprenticeship hours',4);
END $$;

INSERT INTO academic_rule_sets(program_id,rule_scope,rule_name,source_url,notes) VALUES
('8800BTECH','CONTINUATION','Capstone and graduation work experience','https://www.bcit.ca/programs/construction-management-bachelor-of-technology-full-time-part-time-8800btech/','Admission work experience counts toward the two-year total.'),
('8800BTECH','COMPLETION','Professional Standards capstone choice','https://www.bcit.ca/programs/construction-management-bachelor-of-technology-full-time-part-time-8800btech/','CMGT 8700 followed by one of CMGT 8800 or CMGT 8810.') ON CONFLICT DO NOTHING;

-- Generalized non-course prerequisite conditions and exact course prerequisite groups.
INSERT INTO courses(course_id,course_name,status,notes) VALUES
('CMGT7205','External/pre-program prerequisite CMGT 7205','Active','Referenced by Program 4 prerequisite data; overview not supplied in workbook.'),
('CMGT7100','External/pre-program prerequisite CMGT 7100','Active','Referenced by Program 4 prerequisite data; overview not supplied in workbook.'),
('CMGT7800','External/pre-program prerequisite CMGT 7800','Active','Referenced by Program 4 prerequisite data; overview not supplied in workbook.'),
('BLDT2091','External/pre-program prerequisite BLDT 2091','Active','Referenced by Program 4 prerequisite data; overview not supplied in workbook.'),
('CMGT7110','External/pre-program prerequisite CMGT 7110','Active','Referenced by Program 4 prerequisite data; overview not supplied in workbook.'),
('TMGT7122','External/pre-program prerequisite TMGT 7122','Active','Referenced by Program 4 prerequisite data; overview not supplied in workbook.'),
('ENGL1177','English 1177','Active','Referenced as an equivalent prerequisite option.')
ON CONFLICT(course_id) DO NOTHING;

INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT7160','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT7160');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7160' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT7190','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT7190');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7190' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT7211','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT7211');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7190','50','COURSE','Course prerequisite from official source','50% in CMGT 7190 and  Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7211' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7190');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','50% in CMGT 7190 and  Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7211' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT7400','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT7400');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7211','50','COURSE','Course prerequisite from official source','50% in CMGT 7211 and 50% in CMGT 7810, and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7400' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7211');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7810','50','COURSE','Course prerequisite from official source','50% in CMGT 7211 and 50% in CMGT 7810, and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7400' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7810');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','50% in CMGT 7211 and 50% in CMGT 7810, and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7400' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT7330','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT7330');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','Admission to the BTech Construction Management degree program' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7330' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT7420','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT7420');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7330','50','COURSE','Course prerequisite from official source','50% in CMGT 7330 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7420' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7330');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','50% in CMGT 7330 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7420' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT8435','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT8435');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8435' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT7535','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT7535');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7535' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT7660','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT7660');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7660' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT8602','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT8602');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7535','50','COURSE','Course prerequisite from official source','50% in CMGT 7535 and 50% in CMGT 7660 and 50% in CMGT 7810 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8602' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7535');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7660','50','COURSE','Course prerequisite from official source','50% in CMGT 7535 and 50% in CMGT 7660 and 50% in CMGT 7810 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8602' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7660');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7810','50','COURSE','Course prerequisite from official source','50% in CMGT 7535 and 50% in CMGT 7660 and 50% in CMGT 7810 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8602' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7810');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','50% in CMGT 7535 and 50% in CMGT 7660 and 50% in CMGT 7810 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8602' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT7125','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT7125');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7190','50','COURSE','Course prerequisite from official source','50% in CMGT 7190 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7125' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7190');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','50% in CMGT 7190 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7125' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT7220','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT7220');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7205','50','COURSE','Course prerequisite from official source','50% in CMGT 7205 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7220' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7205');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','50% in CMGT 7205 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7220' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT7605','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT7605');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7605' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT7840','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT7840');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7100','50','COURSE','Course prerequisite from official source','50% in CMGT 7100 and 50% in CMGT 7800 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7840' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7100');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7800','50','COURSE','Course prerequisite from official source','50% in CMGT 7100 and 50% in CMGT 7800 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7840' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7800');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','50% in CMGT 7100 and 50% in CMGT 7800 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7840' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT8040','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT8040');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'BLDT2091','50','COURSE','Course prerequisite from official source','50% in BLDT 2091 and 50% in CMGT 7205 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8040' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='BLDT2091');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7205','50','COURSE','Course prerequisite from official source','50% in BLDT 2091 and 50% in CMGT 7205 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8040' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7205');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','50% in BLDT 2091 and 50% in CMGT 7205 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8040' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT8050','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT8050');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'BLDT2091','50','COURSE','Course prerequisite from official source','50% in BLDT 2091 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8050' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='BLDT2091');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','50% in BLDT 2091 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8050' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT8060','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT8060');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7110','50','COURSE','Course prerequisite from official source','50% in CMGT 7110 and 50% in CMGT 7330 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8060' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7110');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7330','50','COURSE','Course prerequisite from official source','50% in CMGT 7110 and 50% in CMGT 7330 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8060' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7330');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','50% in CMGT 7110 and 50% in CMGT 7330 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8060' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'TMGT7112','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='TMGT7112');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'TMGT7111','50','COURSE','Course prerequisite from official source','50% in TMGT 7111' FROM prerequisite_groups pg WHERE pg.course_id='TMGT7112' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='TMGT7111');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'TMGT7113','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='TMGT7113');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'TMGT7111','50','COURSE','Course prerequisite from official source','50% in TMGT 7111' FROM prerequisite_groups pg WHERE pg.course_id='TMGT7113' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='TMGT7111');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'TMGT7121','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='TMGT7121');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'TMGT7122','50','COURSE','Course prerequisite from official source','50% in TMGT 7122' FROM prerequisite_groups pg WHERE pg.course_id='TMGT7121' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='TMGT7122');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'LIBS7001','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='LIBS7001');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'ENGL1177',NULL,'COURSE','Course prerequisite from official source','50% in BCIT ENGL 1177 or equivalent, or 6 credits BCIT Communication at 1100-level or above, or 3 credits of a university/college first-year social science or humanities course.' FROM prerequisite_groups pg WHERE pg.course_id='LIBS7001' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='ENGL1177');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'LIBS7002','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='LIBS7002');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'ENGL1177',NULL,'COURSE','Course prerequisite from official source','BCIT ENGL 1177, or 6 credits BCIT Communication at 1100-level or above, or 3 credits of a university/college first-year social science or humanities course.' FROM prerequisite_groups pg WHERE pg.course_id='LIBS7002' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='ENGL1177');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'LIBS7013','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='LIBS7013');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'ENGL1177',NULL,'COURSE','Course prerequisite from official source','BCIT ENGL 1177, or 6 credits BCIT Communication at 1100-level or above, or 3 credits of a university/college first-year social science or humanities course.' FROM prerequisite_groups pg WHERE pg.course_id='LIBS7013' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='ENGL1177');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT7810','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT7810');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT7810' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT8211','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT8211');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7810','50','COURSE','Course prerequisite from official source','50% in CMGT 7810 and 50% in CMGT 7660 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8211' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7810');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT7660','50','COURSE','Course prerequisite from official source','50% in CMGT 7810 and 50% in CMGT 7660 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8211' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT7660');
INSERT INTO prerequisite_conditions(prerequisite_group_id,required_program_id,condition_type,description,notes) SELECT prerequisite_group_id,'8800BTECH','PROGRAM_ADMISSION','Admission to the BTech Construction Management degree program','50% in CMGT 7810 and 50% in CMGT 7660 and Admission to the BTech Construction Management degree program.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8211' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='PROGRAM_ADMISSION');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT8700','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT8700');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT8800',NULL,'COURSE','Course prerequisite from official source','Successful completion of all program courses (with exception of CMGT 8800). Corequisites: Minimum of 2 years Related Work Experience; Industry Topic; and an Industry Sponsor.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8700' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT8800');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT8800','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT8800');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT8700','50','COURSE','Course prerequisite from official source','50% in CMGT 8700 and Department approval.' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8800' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT8700');
INSERT INTO prerequisite_groups(course_id,group_type) SELECT 'CMGT8810','AND' WHERE NOT EXISTS(SELECT 1 FROM prerequisite_groups WHERE course_id='CMGT8810');
INSERT INTO prerequisite_conditions(prerequisite_group_id,prerequisite_course_id,minimum_grade,condition_type,description,notes) SELECT prerequisite_group_id,'CMGT8700','50','COURSE','Course prerequisite from official source','50% in CMGT 8700 and Departmental approval' FROM prerequisite_groups pg WHERE pg.course_id='CMGT8810' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type='COURSE' AND pc.prerequisite_course_id='CMGT8700');

-- CMGT 8700 generalized non-course/capstone conditions.
INSERT INTO prerequisite_conditions(prerequisite_group_id,condition_type,minimum_grade,parameters,description,notes)
SELECT pg.prerequisite_group_id,v.condition_type,v.minimum_grade,v.parameters::jsonb,v.description,v.description FROM prerequisite_groups pg CROSS JOIN (VALUES
('PROGRAM_COURSES_COMPLETE_EXCEPT',NULL,'{"except":["CMGT8800","CMGT8810"]}','Successful completion of all program courses except the final project'),
('WORK_EXPERIENCE','2','{"unit":"YEAR","field":"related","admission_experience_counts":true}','Minimum 2 years related work experience total'),
('INDUSTRY_TOPIC',NULL,'{}','Approved industry topic'),('INDUSTRY_SPONSOR',NULL,'{}','Industry sponsor')) v(condition_type,minimum_grade,parameters,description)
WHERE pg.course_id='CMGT8700' AND NOT EXISTS(SELECT 1 FROM prerequisite_conditions pc WHERE pc.prerequisite_group_id=pg.prerequisite_group_id AND pc.condition_type=v.condition_type);
COMMIT;
